inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'lib/tasks/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'config.ru'
    - bin/*
    # TODO remove
    - spec/acceptance_helper.rb
    - spec/acceptance/*
