# .rubocop.yml
AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  Exclude:
    - 'db/**/*' 
    - 'bin/**/*' 

Layout/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: single_quotes