branch-defaults:
  achievments:
    environment: staging
environment-defaults:
  staging:
    branch: null
    repository: null
global:
  application_name: webmoney
  default_ec2_keyname: webmoney-stag
  default_platform: Ruby 3.0 running on 64bit Amazon Linux 2
  default_region: sa-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: webmoney-user
  sc: git
  workspace_type: Application
