default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: <%= ENV['DATABASE_HOST'] || localhost %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: web_money_development

test:
  <<: *default
  database: web_money_test

production:
  <<: *default
  database: web_money_production
