default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: web_money_development

test:
  <<: *default
  database: web_money_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: web_money_production
