default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  # remove if local running
  # host: postgres
  # user: postgres
  # password: password

development:
  <<: *default
  database: web_money_development

test:
  <<: *default
  database: web_money_test

production:
  <<: *default
  database: <%= ENV['RDS_DATABASE'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOST'] %>
  port: 5432
