!include <C4/C4_Container>

@startjson C4_Elements

  {"id":1,"price_cents":"667.0","price_currency":"BRL","date":"2022-09-30","created_at":"2023-07-29T22:02:45.312Z","updated_at":"2023-07-29T22:02:45.312Z","user_profile_id":1,"category_id":9,"account_id":1,"description":"Laborum sint assumenda harum dignissimos?","bill_id":null}

@endjson
