name: Style Guide
on:
  pull_request:
    types: [synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.6'
      - run: gem install rubocop
      - run: rubocop
